### ISSUE TITLE
Is anyone updating these samples?

### ISSUE THREAD

**Issue by aaronksaunders** [KinveyApps/StatusShare-iOS#6]
They dont work...

**Comment by heyzooi** [comment]
We update the samples periodically / when needed.
I tried running this sample.
Can you elaborate on what issues you saw?
Did you changed the appKey and appSecret to your own values in the file AppDelegate.m?

**Comment by aaronksaunders** [comment]
When you tried running it, did it work?

and yes i changed the appKey and appSecret

**Comment by heyzooi** [comment]
Yes, it did work. What kind of error message did you get? It was a compiler error? Or something went wrong during runtime?

**Comment by aaronksaunders** [comment]
Transport error from iOS

On Monday, February 15, 2016, Victor Hugo Barros <notifications@github.com>
wrote:

> Yes, it did work. What kind of error message did you get? It was a
> compiler error? Or something went wrong during runtime?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KinveyApps/StatusShare-iOS/issues/6#issuecomment-184250603>
> .
>


-- 

--

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders




This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by heyzooi** [comment]
We just update the sample project to use our latest SDK version which solves the Transport error.
Please try again.

**Comment by trpmap93** [comment]
Could you provide your samples in Swift as well?  It would greatly help those of us that started developing within the last 2 years.  Thanks!

**Comment by tejasranade** [comment]
@trpmap93 We're providing Swift samples for the new 3.0 version of the Kinvey iOS SDK (currently in Beta). You can get started with our Swift [starter app](https://github.com/KinveyApps/IOS-Starter).

**Comment by aaronksaunders** [comment]
thanks
